### ISSUE TITLE
Other Manufacturer Codes

### ISSUE THREAD

**Issue by gabsi55** [sbender9/signalk-empirbus-plugin#17]
Is it possible to add another manufacturer Codes to open the possibility to Mastervolt/CZone digital switching?
Log now if switching commands are sent on NEMA2000. Thanks in advance.

PGN 65280 ignored:
 {
  prio: 7,
  pgn: 65280,
  dst: 255,
  src: 3,
  timestamp: '2023-08-11T07:06:44.235Z',
  fields: {
    'Manufacturer Code': 'BEP Marine',
    'Industry Code': 'Marine',
    Data: '274961793032'
  },
  description: 'Manufacturer Proprietary single-frame non-addressed'
}

**Comment by Krillle** [comment]
The signalk-empirbus-plugin processes the application-specific PGN 65280 in a manner tailored to EmpirBus. These messages are transmitted by a designated counterpart, which requires manual setup within the EmpirBus programming/configuration. For details on this setup refer to [1].

The signalk-empirbus-plugin plugin relies on the EmpirBus "Data Model 2" to read and write the status for 2 dimmers and 6 switches. The first 4 bytes of PGN 65280 together with the first 2 bits of byte 5 represent the dimmers with values 0..1000, the remaining 6 bits can be used for up to 6 switches with values 0|1. See "EmpirBus Data Model 2" in [2].

We can indeed parse these messages from Mastervolt/CZone, also known as BEP Marine. However, you would need to ensure that the PGN 65280 are transmitted and processed in the exact same manner within the Mastervolt installation. I couldn't find any specifics regarding the information Mastervolt sends using PGN 65280, but it's very likely tailored specifically for Mastervolt.

[1] https://github.com/sbender9/signalk-empirbus-plugin/blob/master/docs/How%20to%20process%20data%20in%20EmpirBus%20GUI.pdf
[2] https://github.com/sbender9/signalk-empirbus-plugin/blob/master/docs/PGN%2065280%20EmpirBus%20Application%20Specific%20PGN.pdf

**Comment by Krillle** [comment]
Closing as Mastervolt Switching integration is too specific
